import { 
  HiFilter, 
  HiSwitchVertical, 
  HiPlus, 
  HiScissors  } from 'react-icons/hi'
import { 
  GiBull, 
  GiCow, 
  GiFemale, 
  GiHelp, 
  GiMale, 
  GiCardboardBox, 
  GiCorkedTube, 
  GiIceCube, 
  GiMedicines, 
  GiReceiveMoney, 
  GiWeight, 
  GiScissors, 
  GiEmbryo, 
  GiSyringe, 
  GiMoneyStack, 
  GiSeedling, 
  GiPawHeart,
  GiHighGrass,
  GiHamburgerMenu,
  GiFallDown,
  GiMoon,
  GiSun,
  GiCancel,
  GiPadlockOpen, 
  GiPencil
} from 'react-icons/gi'
import { FaCow } from 'react-icons/fa6'
import { MdAgriculture } from 'react-icons/md'
import { FiBell, FiSettings } from 'react-icons/fi'
import { LuX } from "react-icons/lu"

export const Icons = { 
  HiFilter, 
  HiSwitchVertical, 
  HiPlus,
  HiScissors,
  GiBull, 
  GiCow, 
  GiFemale, 
  GiHelp, 
  GiMale, 
  GiCardboardBox, 
  GiCorkedTube, 
  GiIceCube, 
  GiMedicines, 
  GiReceiveMoney, 
  GiWeight, 
  GiScissors, 
  GiEmbryo, 
  GiSyringe, 
  GiMoneyStack, 
  GiSeedling, 
  GiPawHeart,
  GiHighGrass,
  GiHamburgerMenu,
  GiFallDown,
  GiMoon,
  GiSun,
  GiCancel,
  GiPadlockOpen, 
  GiPencil,
  FaCow,
  MdAgriculture,
  FiBell,
  FiSettings,
  LuX,
}