export type AngusTechResponse = {
  result: {
    tql: {
      isValid: boolean,
      message: string,
      errorLine: number,
      errorColumn: number,
      expressionString: string,
      expressionTree: {
          type: string,
          fieldId: string,
          operatorId: string,
          value: string
      },
      expected: [
          {
              name: string,
              title: string
          },
          {
              name: string,
              title: string
          }
      ]
    },
    rows: Array<AngusTechBeastData>,
    currentPage: number,
    previousPage: number,
    nextPage: number,
    totalPages: number,
    firstItem: number,
    lastItem: number,
    totalItems: number,
    duration: number,
  }, 
}

export type EbvDef = {
  angusTechFieldNameValue: string | null,
  angusTechFieldNameAccuracy: string | null,
  angusTechFieldNamePercentile: string | null,
  id: string,
}

export type EbvDefs = Array<EbvDef>

export type AngusTechBeastData = {
  id: string,
  idSortVal: string,
  idWithPhotoIcon: string,
  hasPicture: boolean,
  hasVideo: boolean,
  beastName: string,
  beastNameFull: string,
  beastNameNoSuffix: string,
  pvSuffix: string,
  colour: string,
  sex: string,
  birthDate: string,
  tattoo: string,
  runName: string,
  reg: string,
  invSeason: string,
  birthYear: number,
  status: string,
  nlis: string,
  rfid: string,
  birthNumber: string,
  matingType: string,
  am: string,
  previewAttachKey: string,
  fullsizeAttachKey: string,
  ca: string,
  dd: string,
  nh: string,
  genCondStr: string,
  genTraitStr: string,
  rgStat: string | undefined,
  maStat: string | undefined,
  osStat: string | undefined,
  mhStat: string | undefined,
  dwStat: string | undefined,
  ohStat: string | undefined,
  piStat: string | undefined,
  snpOnFile: boolean,
  mipOnFile: boolean,
  traitsObserved: string,
  numHerds: number,
  genProg: string | undefined,
  progenyCnt: number,
  analProgenyCnt: number,
  actualProgenyCnt: string | undefined,
  actualProgCnt: number,
  actualProgenyCntOther: string | undefined,
  ebvLabels: string | undefined,
  reportCode: string,
  snpCnt: number,
  rbvTraitsObserved: string | undefined,
  sireKey: number,
  sortSireId: string,
  sireId: string,
  sireName: string,
  sireNameNoSuffix: string,
  sirePvSuffix: string,
  sortDamId: string,
  isDonorDam: boolean | undefined,
  paternalSireId: string,
  owner: string,
  herdId: string,
  breederAcctKey: number,
  breederAcctId: string,
  breederPostcode: number,
  isForSale: string | undefined,
  hasSemenAvail: string | undefined,
  showSemenRestrictMsg: boolean,
  asbpCohort: string | undefined,
  cedVal: string | undefined,
  cemVal: string | undefined,
  glVal: string | undefined,
  bwVal: string | undefined,
  wwVal: string | undefined,
  ywVal: string | undefined,
  fwVal: string | undefined,
  mcwVal: string | undefined,
  milkVal: string | undefined,
  dcVal: string | undefined,
  scrotalVal: string | undefined,
  docilityVal: string | undefined,
  feedNfeVal: string | undefined,
  carcWtVal: string | undefined,
  carcEmaVal: string | undefined,
  carcRibFatVal: string | undefined,
  carcRumpFatVal: string | undefined,
  carcRbyVal: string | undefined,
  carcImfVal: string | undefined,
  angleVal: string | undefined,
  clawVal: string | undefined,
  rlsvVal: string | undefined,
  breedingIdxVal: string | undefined,
  domesticIdxVal: string | undefined,
  grainIdxVal: string | undefined,
  grassIdxVal: string | undefined,
  mbcVal: string | undefined,
  mchVal: string | undefined,
  carcMarblingVal: number,
  tendernessVal: number,
  ctVal: number | undefined,
  immuneIdxVal: number,
  abilIdxVal: number,
  domlIdxVal: number,
  grnlIdxVal: number,
  grslIdxVal: number,
  abiIdxVal: number,
  domIdxVal: number,
  grnIdxVal: number,
  grsIdxVal: number,
  proIdxVal: number,
  atsIdxVal: number,
  cedSort: number,
  cemSort: number,
  glSort: number,
  bwSort: number,
  wwSort: number,
  ywSort: number,
  fwSort: number,
  mcwSort: number,
  milkSort: number,
  dcSort: number,
  scrotalSort: number,
  docilitySort: number,
  feedNfeSort: number,
  carcWtSort: number,
  carcEmaSort: number,
  carcRibFatSort: number,
  carcRumpFatSort: number,
  carcRbySort: number,
  carcImfSort: number,
  angleSort: number,
  clawSort: number,
  rlsvSort: number,
  breedingIdxSort: number | undefined,
  domesticIdxSort: number | undefined,
  grainIdxSort: number | undefined,
  grassIdxSort: number | undefined,
  mbcSort: number,
  mchSort: number,
  carcMarblingSort: number,
  tendernessSort: number,
  ctSort: number,
  immuneIdxSort: number,
  abilIdxSort: number,
  domlIdxSort: number,
  grnlIdxSort: number,
  grslIdxSort: number,
  abiIdxSort: number,
  domIdxSort: number,
  grnIdxSort: number,
  grsIdxSort: number,
  proIdxSort: number,
  atsIdxSort: number,
  custom1IdxSort: number,
  custom2IdxSort: number,
  custom3IdxSort: number,
  custom4IdxSort: number,
  custom5IdxSort: number,
  ced: number,
  cem: number,
  gl: number,
  bw: number,
  ww: number,
  yw: number,
  fw: number,
  mcw: number,
  milk: number,
  dc: number,
  scrotal: number,
  docility: number,
  feedNfe: number,
  carcWt: number,
  carcEma: number,
  carcRibFat: number,
  carcRumpFat: number,
  carcRby: number,
  carcImf: number,
  angle: number,
  claw: number,
  rlsv: number,
  breedingIdx: number | undefined,
  domesticIdx: number | undefined,
  grainIdx: number | undefined,
  grassIdx: number | undefined,
  mbc: number | undefined,
  mch: number | undefined,
  carcMarbling: number,
  tenderness: number,
  ct: number | undefined,
  immuneIdx: number,
  abilIdx: string,
  domlIdx: string,
  grnlIdx: string,
  grslIdx: string,
  abiIdx: string,
  domIdx: string,
  grnIdx: string,
  grsIdx: string,
  proIdx: string,
  atsIdx: string,
  cedAcc: string,
  cemAcc: string,
  glAcc: string,
  bwAcc: string,
  wwAcc: string,
  ywAcc: string,
  fwAcc: string,
  mcwAcc: string,
  milkAcc: string,
  dcAcc: string,
  scrotalAcc: string,
  docilityAcc: string,
  feedNfeAcc: string,
  carcWtAcc: string,
  carcEmaAcc: string,
  carcRibFatAcc: string,
  carcRumpFatAcc: string,
  carcRbyAcc: string,
  carcImfAcc: string,
  angleAcc: string,
  clawAcc: string,
  rlsvAcc: string,
  breedingIdxAcc: string | undefined,
  domesticIdxAcc: string | undefined,
  grainIdxAcc: string | undefined,
  grassIdxAcc: string | undefined,
  mbcAcc: string | undefined,
  mchAcc: string | undefined,
  carcMarblingAcc: string,
  tendernessAcc: string,
  ctAcc: string | undefined,
  immuneIdxAcc: string,
  abilIdxAcc: string | undefined,
  domlIdxAcc: string | undefined,
  grnlIdxAcc: string | undefined,
  grslIdxAcc: string | undefined,
  abiIdxAcc: string | undefined,
  domIdxAcc: string | undefined,
  grnIdxAcc: string | undefined,
  grsIdxAcc: string | undefined,
  proIdxAcc: string | undefined,
  atsIdxAcc: string | undefined,
  cedPerc: string,
  cemPerc: string,
  glPerc: string,
  bwPerc: string,
  wwPerc: string,
  ywPerc: string,
  fwPerc: string,
  mcwPerc: string,
  milkPerc: string,
  dcPerc: string,
  scrotalPerc: string,
  docilityPerc: string,
  feedNfePerc: string,
  carcWtPerc: string,
  carcEmaPerc: string,
  carcRibFatPerc: string,
  carcRumpFatPerc: string,
  carcRbyPerc: string,
  carcImfPerc: string,
  anglePerc: string,
  clawPerc: string,
  rlsvPerc: string,
  breedingIdxPerc: string | undefined,
  domesticIdxPerc: string | undefined,
  grainIdxPerc: string | undefined,
  grassIdxPerc: string | undefined,
  mbcPerc: string | undefined,
  mchPerc: string | undefined,
  carcMarblingPerc: string,
  tendernessPerc: string,
  ctPerc: string,
  immuneIdxPerc: string,
  abilIdxPerc: string,
  domlIdxPerc: string,
  grnlIdxPerc: string,
  grslIdxPerc: string,
  abiIdxPerc: string,
  domIdxPerc: string,
  grnIdxPerc: string,
  grsIdxPerc: string,
  proIdxPerc: string,
  atsIdxPerc: string,
  cedProg: number,
  cemProg: number,
  glProg: number,
  bwProg: number,
  wwProg: number,
  ywProg: number,
  fwProg: number,
  mcwProg: number,
  milkProg: number,
  dcProg: number,
  scrotalProg: number,
  docilityProg: number,
  feedNfeProg: number,
  carcWtProg: number,
  carcEmaProg: number,
  carcRibFatProg: number,
  carcRumpFatProg: number,
  carcRbyProg: number,
  carcImfProg: number,
  angleProg: number,
  clawProg: number,
  rlsvProg: number,
  mbcProg: number | undefined,
  mchProg: number | undefined,
  carcMarblingProg: number,
  tendernessProg: number,
  ctProg: number | undefined,
  immuneIdxProg: number | undefined,
  damKey: number | undefined,
  damName: string | undefined,
  damNameNoSuffix: string | undefined,
  damPvSuffix: string | undefined,
  maternalSireId: string | undefined,
  custom1IdxVal: string | undefined,
  custom2IdxVal: string | undefined,
  custom3IdxVal: string | undefined,
  custom4IdxVal: string | undefined,
  custom5IdxVal: string | undefined,
  custom1Idx: string | undefined,
  custom2Idx: string | undefined,
  custom3Idx: string | undefined,
  custom4Idx: string | undefined,
  custom5Idx: string | undefined,
  custom1IdxAcc: string | undefined,
  custom2IdxAcc: string | undefined,
  custom3IdxAcc: string | undefined,
  custom4IdxAcc: string | undefined,
  custom5IdxAcc: string | undefined,
  custom1IdxPerc: string | undefined,
  custom2IdxPerc: string | undefined,
  custom3IdxPerc: string | undefined,
  custom4IdxPerc: string | undefined,
  custom5IdxPerc: string | undefined,
  damId: string | undefined,
  progInCat: string | undefined,
  catLotId: string | undefined,
  sortLotId: string | undefined,
  catDescr: string | undefined,
  lotIdAndName: string | undefined
}