services:
  database:
    image: docker.io/library/mongo:latest
    container_name: mongo
    networks: 
      - backend
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example 
    restart: always
    volumes:
      - ~/.mongo:/data/db
    command:
      - mongod --replSet
    ports:
      - 27017:27017

networks:
  # The presence of these objects is sufficient to define them
  frontend: {}
  backend: {}